### ISSUE TITLE
Wie ruft man die Api auf ?

### ISSUE THREAD

**Issue by ghost** [TheNoim/DSBAPI#1]
Ich check nicht ganz wie ich den Stundeplan mit meinen Daten abrufe :thinking:. Ich hab mir schon die Tutorials zu Klassen in Javascript angeschaut aber ich kann diese einfach nicht aufrufen :sob:  Könntest du das vielleicht kurz zeigen ? Wäre nett :smile:

**Comment by TheNoim** [comment]
Hallo, natürlich kann ich das machen. Was nutzt du? NodeJS? Oder ganz normal im Browser ? 
LG

**Comment by ghost** [comment]
Ich nutze eigentlich einen ganz normalen Webserver... brauche ich Node.js ?
Oder was genau meist du ? :)

**Comment by TheNoim** [comment]
Nein. Aber ich habe die Library darauf ausgelegt. Ich kann Morgen Abend eine Browser Version pushen und dann ein Beispiel angeben wie du es nutzen kannst. :)

**Comment by ghost** [comment]
Ok danke das wäre nett  ^^

**Comment by TheNoim** [comment]
Ich habe jetzt eine Browser Version commited. Sie befindet sich im Browser Ordner.
Um sie nun zu nutzen, musst du nicht viel tuen.
```javascript
var dsb = new DSBLib("username", "password");
// Ich weiß nicht ob du weißt wie Promises funktionieren, also erkläre ich es mit und ohne.
// Du hast zwei Möglichkeiten. Einmal die alte API zu nutzen, oder die neue.
// Die neue hat den Nachteil, dass den JSON den du zurück bekommst etwas wirr ist, aber weil das die selbe ist, die auch die Offizielle Seite (http://mobile.dsbcontrol.de/) nutzt, denke ich, wird die am längsten verfügbar sein.
// Die alte hat den Vorteil sie ist sehr einfach zu verstehen, aber es könnte sein das sie in Zukunft obsolet wird. 

// Die alte (mit Promise):
dsb.getDataV1().then(function(Data) {
    console.log(Data);
}).catch(console.error);
// Mit callback
dsb.getDataV1(function(error, Data) {
    if (!error) {
        console.log(Data);
    } else {
        console.error(error);
    }
});
// Die neue (mit Promise)
dsb.getData().then(function(Data) {
    console.log(Data);
}).catch(console.error);
// Mit callback
dsb.getData(function(error, Data) {
    if (!error) {
        console.log(Data);
    } else {
        console.error(error);
    }
});
```
Ich habe die Browser Version jetzt nicht getestet, aber so sollte es gehen. Ich weiß auch nicht so wirklich wieso man es Client Seitig nutzen sollte. Ich habe es eher als Server Library ausgelegt.
